services:
  postgres:
    image: postgres:15-alpine
    container_name: sap-service-agent-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sap_service_agent_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - sap-service-agent-network

  tenant-db-setup:
    build:
      context: ./scripts
      dockerfile: Dockerfile
    container_name: sap-service-agent-tenant-db-setup
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      TENANT_IDS: 550e8400-e29b-41d4-a716-446655440000,550e8400-e29b-41d4-a716-446655440001
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sap-service-agent-network

  backend:
    build:
      context: ./sap-service-agent-backend
      dockerfile: Dockerfile
      target: production
    container_name: sap-service-agent-backend
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: sap_service_agent_auth
      PORT: 3000
      NODE_ENV: production
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRES_IN: 1h
      TENANT_IDS: 550e8400-e29b-41d4-a716-446655440000,550e8400-e29b-41d4-a716-446655440001
    command: ["sh", "-c", "npm run migration:run:all && npm run start:prod"]
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      tenant-db-setup:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/auth/tenants"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - sap-service-agent-network

  worker:
    build:
      context: ./sap-service-agent-backend
      dockerfile: Dockerfile
      target: production
    container_name: sap-service-agent-worker
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: sap_service_agent_auth
      NODE_ENV: production
      WORKER_INTERVAL_SECONDS: 10
      TENANT_DATABASES: 550e8400-e29b-41d4-a716-446655440000:tenant_alpha_db,550e8400-e29b-41d4-a716-446655440001:tenant_beta_db
    command: ["sh", "-c", "npm run migration:run:all && node dist/src/apps/requests-agent-worker/main"]
    depends_on:
      postgres:
        condition: service_healthy
      tenant-db-setup:
        condition: service_completed_successfully
    networks:
      - sap-service-agent-network

  frontend:
    build:
      context: ./sap-service-agent-frontend
      dockerfile: Dockerfile
      target: production
    container_name: sap-service-agent-frontend
    restart: unless-stopped
    ports:
      - "4200:4200"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - sap-service-agent-network

  data-seeder:
    build:
      context: ./data-seeder
      dockerfile: Dockerfile
    container_name: sap-service-agent-data-seeder
    environment:
      BACKEND_URL: http://backend:3000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - sap-service-agent-network

networks:
  sap-service-agent-network:
    driver: bridge

volumes:
  postgres_data:
